# Generated by Django 4.0.3 on 2022-04-08 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_platform', '0002_alter_embed_ownership_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='embed_enforcement_image',
            name='user_info',
            field=models.ForeignKey(max_length=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_platform.user_info'),
        ),
        migrations.AddField(
            model_name='embed_enforcement_sound',
            name='user_info',
            field=models.ForeignKey(max_length=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_platform.user_info'),
        ),
        migrations.AddField(
            model_name='embed_enforcement_text',
            name='user_info',
            field=models.ForeignKey(max_length=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_platform.user_info'),
        ),
        migrations.AddField(
            model_name='embed_ownership_sound',
            name='user_info',
            field=models.ForeignKey(max_length=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_platform.user_info'),
        ),
        migrations.AddField(
            model_name='embed_ownership_text',
            name='user_info',
            field=models.ForeignKey(max_length=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_platform.user_info'),
        ),
    ]
