# Generated by Django 4.0.4 on 2022-04-14 16:05

from django.db import migrations, models
import my_platform.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_platform', '0003_embed_enforcement_image_user_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embed_enforcement_image',
            name='hash_url',
            field=models.CharField(default=my_platform.models._createHash, max_length=10),
        ),
        migrations.AddField(
            model_name='embed_enforcement_sound',
            name='hash_url',
            field=models.CharField(default=my_platform.models._createHash, max_length=10),
        ),
        migrations.AddField(
            model_name='embed_enforcement_text',
            name='hash_url',
            field=models.CharField(default=my_platform.models._createHash, max_length=10),
        ),
        migrations.AddField(
            model_name='embed_ownership_image',
            name='hash_url',
            field=models.CharField(default=my_platform.models._createHash, max_length=10),
        ),
        migrations.AddField(
            model_name='embed_ownership_sound',
            name='hash_url',
            field=models.CharField(default=my_platform.models._createHash, max_length=10),
        ),
        migrations.AddField(
            model_name='embed_ownership_text',
            name='hash_url',
            field=models.CharField(default=my_platform.models._createHash, max_length=10),
        ),
        migrations.AlterField(
            model_name='embed_enforcement_sound',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='sound/'),
        ),
        migrations.AlterField(
            model_name='embed_enforcement_text',
            name='file',
            field=models.FileField(upload_to='text/'),
        ),
        migrations.AlterField(
            model_name='embed_ownership_sound',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='sound/'),
        ),
        migrations.AlterField(
            model_name='embed_ownership_text',
            name='file',
            field=models.FileField(upload_to='text/'),
        ),
    ]
