# Generated by Django 4.0.4 on 2022-04-14 16:20

from django.db import migrations, models
import my_platform.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_platform', '0004_embed_enforcement_image_hash_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embed_enforcement_image',
            name='hash_url',
            field=models.CharField(default=my_platform.models._createHash, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='embed_enforcement_sound',
            name='hash_url',
            field=models.CharField(default=my_platform.models._createHash, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='embed_enforcement_text',
            name='hash_url',
            field=models.CharField(default=my_platform.models._createHash, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='embed_ownership_image',
            name='hash_url',
            field=models.CharField(default=my_platform.models._createHash, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='embed_ownership_sound',
            name='hash_url',
            field=models.CharField(default=my_platform.models._createHash, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='embed_ownership_text',
            name='hash_url',
            field=models.CharField(default=my_platform.models._createHash, editable=False, max_length=50),
        ),
    ]
