# Generated by Django 4.0.4 on 2022-04-15 11:25

from django.db import migrations, models
import my_platform.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_platform', '0005_alter_embed_enforcement_image_hash_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embed_enforcement_image',
            name='file',
            field=models.ImageField(upload_to=my_platform.models.UploadToPathAndRename),
        ),
        migrations.AlterField(
            model_name='embed_enforcement_sound',
            name='file',
            field=models.FileField(upload_to='sound/'),
        ),
        migrations.AlterField(
            model_name='embed_ownership_sound',
            name='file',
            field=models.FileField(upload_to='sound/'),
        ),
    ]
