# Generated by Django 4.0.4 on 2022-04-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_platform', '0006_alter_embed_enforcement_image_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extract_Embedded_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('source_file', models.CharField(default='Extraction File', max_length=100)),
                ('file', models.FileField(upload_to='extraction_files/image')),
            ],
        ),
        migrations.CreateModel(
            name='Extract_Embedded_Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('source_file', models.CharField(default='Extraction File', max_length=100)),
                ('file', models.FileField(upload_to='extraction_files/sound')),
            ],
        ),
        migrations.CreateModel(
            name='Extract_Embedded_Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('source_file', models.CharField(default='Extraction File', max_length=100)),
                ('file', models.FileField(upload_to='extraction_files/text')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Extract_Embedded_Info',
        ),
    ]
