# Generated by Django 4.0.4 on 2022-04-25 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_platform', '0007_extract_embedded_image_extract_embedded_sound_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embed_ownership_image',
            name='user_info',
            field=models.ForeignKey(auto_created=True, max_length=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_platform.user_info'),
        ),
        migrations.AlterField(
            model_name='embed_ownership_sound',
            name='user_info',
            field=models.ForeignKey(auto_created=True, max_length=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_platform.user_info'),
        ),
    ]
